#!/usr/bin/env bash
set -euo pipefail

if [ ! -e roo ]
then
  wget https://github.com/outlaw/roo/releases/download/0.0.0-alpha/roo-linux-x86_64.tar.gz
  tar xvf roo-linux-x86_64.tar.gz
#  wget https://github.com/outlaw/roo/releases/download/0.0.0-alpha/roo-darwin-x86_64.tar.gz
#  tar xvf roo-darwin-x86_64.tar.gz
fi

export AWS_PROFILE=nonprod
export AWS_REGION=ap-southeast-2
export ENVIRONMENT=staging

bundle exec ruby get_issues.rb
