#!/usr/bin/env bash
set -euo pipefail

#curl https://raw.githubusercontent.com/apex/apex/master/install.sh | sh
##wget https://github.com/outlaw/roo/releases/download/0.0.0-alpha/roo-linux-x86_64.tar.gz
##tar xvf roo-linux-x86_64.tar.gz
#wget https://github.com/outlaw/roo/releases/download/0.0.0-alpha/roo-darwin-x86_64.tar.gz
#tar xvf roo-darwin-x86_64.tar.gz

export AWS_PROFILE=nonprod
export AWS_REGION=ap-southeast-2
export ENVIRONMENT=staging

bundle exec ruby get_issues.rb
